name: 'dbt_joyeria'
version: '1.0.0'

profile: 'bigquery'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"


models:
  dbt_joyeria:
    # Applies to all files under models/staging/
    staging:
      materialized: table
      +schema: staging
