version: 2

sources:
  - name: source_current
    description: 'Incoming, current data is linked in BigQuery as an external table from Google Sheets.'
    database: source-data-314320
    schema: joyeria_dataset
    tables: 
      - name: gsheet_centro
      - name: gsheet_segovia
      - name: gsheet_patria
      - name: gsheet_pasaje
      - name: gsheet_vallardo
      - name: gsheet_va_en_linea    

  - name: source_historical
    description: 'The growing, historical data is stored in BigQuery.'
    database: source-data-314320
    schema: historical_data
    tables: 
      - name: Centro_2022-02-28
      - name: Segovia_2022-02-28
      - name: Patria_2022-02-28
      - name: Pasaje_2022-02-28
      - name: Vallardo_2022-02-28
      - name: VA_en_linea_2022-02-28

  - name: source_forecast
    description: 'Forecasted data from R using Holt Winters, imported to BigQuery.'
    database: source-data-314320
    schema: joyeria_dataset
    tables: 
      - name: forecast